//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2020.03.22 at 03:06:41 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tags.manfredi.kpi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kpi.manfredi.tags;
